baseurl = "http://example.org"
title = "Matej Jurmanovic"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Matej Jurmanovic" 
  description = "description"
  logo = "fa-diamond"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Matej Jurmanovic"
description = "Matej is an illustrator in Stockholm"

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
description = ""
